# Generated by Django 2.1.4 on 2018-12-21 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tank',
            options={},
        ),
    ]
